### ISSUE TITLE
[req] Cosmos - 260586

### ISSUE THREAD

**Issue by ilike2burnthing** [DuckieTV/SceneNameExceptions#4]
Season 1 was subtitled 'A Spacetime Odyssey', which in some releases was (mis)spelled as 'A Space Time Odyssey', hence the solution was to just search for `Cosmos Odyssey s01e##`.

Season 2 has come out with a new subtitle, 'Possible Worlds' and is being released under that name, however it is incorrectly being released as s01e## rather than s02.

Is it possible to provide a per season fix? If so, season 2 for Cosmos (260586) would need to search for `Cosmos Possible Worlds s01e##`.

If not, I'm not sure what the fix would be other than crippling the search term for Cosmos as a whole to just `Cosmos`, or maybe to ignore the season number and use `Cosmos s01e##`.

**Comment by garfield69** [comment]
Nah.
If the scene has reset the series back to s01 under a new name, then there is no way you can use the existing 260586 to track the new episodes.
your best option is to go to the add-a-series page on Dtv and add the series called `Cosmos Possible Worlds` (378579) and then you are good to go.

**Comment by ilike2burnthing** [comment]
Ah kk, I hadn't seen that 378579 had been added recently, the previous version had been removed after this mess of a discussion - https://forums.thetvdb.com/viewtopic.php?f=7&t=63144

Fingers crossed it stays up!

**Comment by ilike2burnthing** [comment]
And it's down 😞 That thread is even worse now.

I've got my own _fix_ working at the moment, in case anyone else wants a quasi-solution:
1. edit ...\dist\app.js to fetch my own forked SceneNameExceptions.json which has the Cosmos entry removed
2. add `Possible Worlds` to custom search string in DuckieTV (because that's the only one I'm interested in at the moment)^
3. manually edit the season number for each search

Totally worth it! 😛 

I take it there's no way to use the custom search string to remove or replace something in the search query, e.g. `-s02 s01`? I know that example doesn't work, but just in case there's something else.

^steps 1 and 2 obviously could be combined (change Odyssey to Possible Worlds in the .json, rather than removing Cosmos altogether), but I was trying to work out a way to more easily switch between the two.

**Comment by ilike2burnthing** [comment]
@garfield69 can the Cosmos entry be removed? TVDB mods are refusing to budge and are taking down all separate Possible Worlds pages. The most recent attempt (380482) now 404s - https://www.thetvdb.com/series/cosmos-possible-worlds

With the season/series now over, I don't see this changing; and without the ability to alter the name per season, just using `Cosmos` seems like it would cause the least amount of issues. Users can add a custom search string if they like.

**Comment by garfield69** [comment]
okely dokely. removed "260586": "Cosmos Odyssey",

**Comment by ilike2burnthing** [comment]
Ta!
